language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wafeekolatunji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wafeekolatunji/react-test npm run test

after_success:
  script:
  # Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker build -t wafeekolatunji/multi-client ./client
    - docker build -t wafeekolatunji/multi-nginx ./nginx
    - docker build -t wafeekolatunji/multi-server ./server
    - docker build -t wafeekolatunji/multi-worker ./worker


    # Upload images to docker hub
    - docker push wafeekolatunji/multi-client
    - docker push wafeekolatunji/multi-nginx
    - docker push wafeekolatunji/multi-server
    - docker push wafeekolatunji/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-090343325122"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY