language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wafeekolatunji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wafeekolatunji/react-test npm run test

script:
  - bash ./docker-push.sh

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-090343325122"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY